### ISSUE TITLE
OLS-autocomplete link modification

### ISSUE THREAD

**Issue by tschaka1904** [LLTommy/OLS-autocomplete#5]
I was playing a little bit with the OLS-autocomplete examples. This is what I was using: 

```
<form id="local-search" name="local-search" action="http://www.ebi.ac.uk/ols/search" method="get">
  <fieldset>
    <div class="left">
      <label>
        <input style="font-weight: normal" size="35" type="text" name="q" data-olswidget="select" data-olsontology=""
               data-selectpath="http://www.ebi.ac.uk/ols/" olstype="" id="local-searchbox"
               placeholder="Enter the term you are looking for" class="ac_input">
        </input>
      </label>
    </div>
    <div class="right">
      <input type="submit" value="Search" class="submit">
      </input>
    </div>
  </fieldset>
</form>
```

Here is my use case: I would like to able to search for terms in OLS, but when I click on the term I would like to do a search with that in the Complex-Portal. Currently, when I click on a term it is taking me to the regarding OLS page. But, if I change the `action="http://www.ebi.ac.uk/ols/search"` from `<form id="local-search" name="local-search" action="http://www.ebi.ac.uk/ols/search" method="get">` to `action="https://complex-portal.github.io/complex-portal-view/complex/search?quer"`, I can redirect it to the Complex-Portal using the submit button. 

Can I somehow modify the destination for the click event as well?

**Comment by LLTommy** [comment]
Hey ya! Please look at the [example2.html](https://github.com/LLTommy/OLS-autocomplete/blob/master/examples/example2.html) (And check the console log output). This should do what you want.

If you select a term it should print you all available information to the console log. In a separate step I overwrite the ' onSubmitClick()' event (Just printing an alert message in the example) - but you should be able to do with it whatever you want.

**Comment by tschaka1904** [comment]
Yes, that is almost all I need! 👍 Can I retrieve the term itself as well? Or is it only available in the URL of the `iri` field?

**Comment by LLTommy** [comment]
I just made some changes so you can get your requested human readable term as well from the widget. Please check the updated example 2, it should do now what you asked for. 

(However, keep it mind that IRIs are way more specific - and if you need ontology help in general, you know where to find us)

Cheers.

**Comment by LLTommy** [comment]
I think this issue can be close. Please post, re-open or create another issue if you feel otherwise!
