### ISSUE TITLE
Part_of.gif is not provided

### ISSUE THREAD

**Issue by themerius** [LLTommy/OLS-autocomplete#6]
Hi there,

I'm using ols-autocomplete in conjuntion with ols-treeview, and I'll get an error that `ols-autocomplete/img/part_of.gif` is not found.

I think it would be engouh if this `gif` could be provided. See [ols.css](https://github.com/LLTommy/OLS-autocomplete/blob/master/css/ols.css#L178)

Thank you!

**Comment by LLTommy** [comment]
Added that gif so the error msg hopefully disappears. However, I don't think the picture changes anything in the stand alone version of the widget and is a bit of a an artefact, no? So I might change get rid of the picture and the css in the future.

Cheers, thanks for reporting in the meantime!

**Comment by themerius** [comment]
Thank you! Did you also make a release?

**Comment by LLTommy** [comment]
Yes, there should be a new version on npm.

**Comment by themerius** [comment]
Works fine, thanks!
